AWSTemplateFormatVersion: 2010-09-09
Description: "cloudFormation demo"

Parameters:
  Environment:
    Description: Environment Name
    Type: String

Resources: 
  lambdaFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "demo-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogsEvents"
                Resource: "*"
         
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: CloudFormation demo lambda
      FunctionName: !Sub demo-loudformation${Environment}
      Handler: GHActionsCFStudy::GHActionsCFStudy.Function::FunctionHandler
      MemorySize: 128
      Role: !GetAtt lambdaFunctionIamRole.Arn
      Runtime: dotnet6
      Timeout: 20
      Environment:
        Variables:
          key1: value1 # A map of key-value pairs that the Lambda function can access
      Code:
        S3Bucket: demo-loudformation-packages 
        S3Key: lambda.zip
      Tags:
        - Key: keyname
          Value: value